<?php

namespace Rikudou\AwsSdkPhpstan\Types;

final class PollyClientReturnTypeExtension implements \PHPStan\Type\DynamicMethodReturnTypeExtension
{
    /**
     * @return class-string<\Aws\Polly\PollyClient>
     */
    public function getClass(): string
    {
        return \Aws\Polly\PollyClient::class;
    }
    public function isMethodSupported(\PHPStan\Reflection\MethodReflection $methodReflection): bool
    {
        return in_array($methodReflection->getName(), [
            'deleteLexicon',
            'describeVoices',
            'getLexicon',
            'getSpeechSynthesisTask',
            'listLexicons',
            'listSpeechSynthesisTasks',
            'putLexicon',
            'startSpeechSynthesisTask',
            'synthesizeSpeech',
        ], true);
    }
    public function getTypeFromMethodCall(\PHPStan\Reflection\MethodReflection $methodReflection, \PhpParser\Node\Expr\MethodCall $methodCall, \PHPStan\Analyser\Scope $scope): ?\PHPStan\Type\Type
    {
        return match ((string) $methodCall->name) {
            default => throw new \RuntimeException('Unsupported method'),
            'deleteLexicon' => $this->deleteLexicon(),
            'describeVoices' => $this->describeVoices(),
            'getLexicon' => $this->getLexicon(),
            'getSpeechSynthesisTask' => $this->getSpeechSynthesisTask(),
            'listLexicons' => $this->listLexicons(),
            'listSpeechSynthesisTasks' => $this->listSpeechSynthesisTasks(),
            'putLexicon' => $this->putLexicon(),
            'startSpeechSynthesisTask' => $this->startSpeechSynthesisTask(),
            'synthesizeSpeech' => $this->synthesizeSpeech(),
        };
    }
    private function deleteLexicon(): ?\PHPStan\Type\Type
    {
        return new \PHPStan\Type\Generic\GenericObjectType('Aws\Result', [
            new \PHPStan\Type\Constant\ConstantArrayType([], []),
        ]);
    }
    private function describeVoices(): ?\PHPStan\Type\Type
    {
        return new \PHPStan\Type\Generic\GenericObjectType('Aws\Result', [
            new \PHPStan\Type\Constant\ConstantArrayType([
                new \PHPStan\Type\Constant\ConstantStringType('Voices'),
                new \PHPStan\Type\Constant\ConstantStringType('NextToken'),
            ], [
                new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\Constant\ConstantArrayType([
                    new \PHPStan\Type\Constant\ConstantStringType('Gender'),
                    new \PHPStan\Type\Constant\ConstantStringType('Id'),
                    new \PHPStan\Type\Constant\ConstantStringType('LanguageCode'),
                    new \PHPStan\Type\Constant\ConstantStringType('LanguageName'),
                    new \PHPStan\Type\Constant\ConstantStringType('Name'),
                    new \PHPStan\Type\Constant\ConstantStringType('AdditionalLanguageCodes'),
                    new \PHPStan\Type\Constant\ConstantStringType('SupportedEngines'),
                ], [
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('Female'),
                        new \PHPStan\Type\Constant\ConstantStringType('Male'),
                    ]),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('Aditi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Amy'),
                        new \PHPStan\Type\Constant\ConstantStringType('Astrid'),
                        new \PHPStan\Type\Constant\ConstantStringType('Bianca'),
                        new \PHPStan\Type\Constant\ConstantStringType('Brian'),
                        new \PHPStan\Type\Constant\ConstantStringType('Camila'),
                        new \PHPStan\Type\Constant\ConstantStringType('Carla'),
                        new \PHPStan\Type\Constant\ConstantStringType('Carmen'),
                        new \PHPStan\Type\Constant\ConstantStringType('Celine'),
                        new \PHPStan\Type\Constant\ConstantStringType('Chantal'),
                        new \PHPStan\Type\Constant\ConstantStringType('Conchita'),
                        new \PHPStan\Type\Constant\ConstantStringType('Cristiano'),
                        new \PHPStan\Type\Constant\ConstantStringType('Dora'),
                        new \PHPStan\Type\Constant\ConstantStringType('Emma'),
                        new \PHPStan\Type\Constant\ConstantStringType('Enrique'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ewa'),
                        new \PHPStan\Type\Constant\ConstantStringType('Filiz'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gabrielle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Geraint'),
                        new \PHPStan\Type\Constant\ConstantStringType('Giorgio'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gwyneth'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hans'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ines'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ivy'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jacek'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jan'),
                        new \PHPStan\Type\Constant\ConstantStringType('Joanna'),
                        new \PHPStan\Type\Constant\ConstantStringType('Joey'),
                        new \PHPStan\Type\Constant\ConstantStringType('Justin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Karl'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kendra'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kevin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kimberly'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lea'),
                        new \PHPStan\Type\Constant\ConstantStringType('Liv'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lotte'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lucia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lupe'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mads'),
                        new \PHPStan\Type\Constant\ConstantStringType('Maja'),
                        new \PHPStan\Type\Constant\ConstantStringType('Marlene'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mathieu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Matthew'),
                        new \PHPStan\Type\Constant\ConstantStringType('Maxim'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Miguel'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mizuki'),
                        new \PHPStan\Type\Constant\ConstantStringType('Naja'),
                        new \PHPStan\Type\Constant\ConstantStringType('Nicole'),
                        new \PHPStan\Type\Constant\ConstantStringType('Olivia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Penelope'),
                        new \PHPStan\Type\Constant\ConstantStringType('Raveena'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ricardo'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ruben'),
                        new \PHPStan\Type\Constant\ConstantStringType('Russell'),
                        new \PHPStan\Type\Constant\ConstantStringType('Salli'),
                        new \PHPStan\Type\Constant\ConstantStringType('Seoyeon'),
                        new \PHPStan\Type\Constant\ConstantStringType('Takumi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Tatyana'),
                        new \PHPStan\Type\Constant\ConstantStringType('Vicki'),
                        new \PHPStan\Type\Constant\ConstantStringType('Vitoria'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zeina'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zhiyu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Aria'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ayanda'),
                        new \PHPStan\Type\Constant\ConstantStringType('Arlet'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hannah'),
                        new \PHPStan\Type\Constant\ConstantStringType('Arthur'),
                        new \PHPStan\Type\Constant\ConstantStringType('Daniel'),
                        new \PHPStan\Type\Constant\ConstantStringType('Liam'),
                        new \PHPStan\Type\Constant\ConstantStringType('Pedro'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kajal'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hiujin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Laura'),
                        new \PHPStan\Type\Constant\ConstantStringType('Elin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ida'),
                        new \PHPStan\Type\Constant\ConstantStringType('Suvi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ola'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hala'),
                        new \PHPStan\Type\Constant\ConstantStringType('Andres'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sergio'),
                        new \PHPStan\Type\Constant\ConstantStringType('Remi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Adriano'),
                        new \PHPStan\Type\Constant\ConstantStringType('Thiago'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ruth'),
                        new \PHPStan\Type\Constant\ConstantStringType('Stephen'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kazuha'),
                        new \PHPStan\Type\Constant\ConstantStringType('Tomoko'),
                        new \PHPStan\Type\Constant\ConstantStringType('Niamh'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sofie'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lisa'),
                        new \PHPStan\Type\Constant\ConstantStringType('Isabelle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zayd'),
                        new \PHPStan\Type\Constant\ConstantStringType('Danielle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gregory'),
                        new \PHPStan\Type\Constant\ConstantStringType('Burcu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jitka'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sabrina'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jasmine'),
                    ]),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('arb'),
                        new \PHPStan\Type\Constant\ConstantStringType('cmn-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('cy-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('da-DK'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-DE'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-AU'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB-WLS'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-MX'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-CA'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-FR'),
                        new \PHPStan\Type\Constant\ConstantStringType('is-IS'),
                        new \PHPStan\Type\Constant\ConstantStringType('it-IT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ja-JP'),
                        new \PHPStan\Type\Constant\ConstantStringType('hi-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ko-KR'),
                        new \PHPStan\Type\Constant\ConstantStringType('nb-NO'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-NL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pl-PL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-BR'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-PT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ro-RO'),
                        new \PHPStan\Type\Constant\ConstantStringType('ru-RU'),
                        new \PHPStan\Type\Constant\ConstantStringType('sv-SE'),
                        new \PHPStan\Type\Constant\ConstantStringType('tr-TR'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-NZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-ZA'),
                        new \PHPStan\Type\Constant\ConstantStringType('ca-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-AT'),
                        new \PHPStan\Type\Constant\ConstantStringType('yue-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ar-AE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fi-FI'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IE'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('cs-CZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-CH'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-SG'),
                    ]),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('arb'),
                        new \PHPStan\Type\Constant\ConstantStringType('cmn-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('cy-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('da-DK'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-DE'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-AU'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB-WLS'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-MX'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-CA'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-FR'),
                        new \PHPStan\Type\Constant\ConstantStringType('is-IS'),
                        new \PHPStan\Type\Constant\ConstantStringType('it-IT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ja-JP'),
                        new \PHPStan\Type\Constant\ConstantStringType('hi-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ko-KR'),
                        new \PHPStan\Type\Constant\ConstantStringType('nb-NO'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-NL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pl-PL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-BR'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-PT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ro-RO'),
                        new \PHPStan\Type\Constant\ConstantStringType('ru-RU'),
                        new \PHPStan\Type\Constant\ConstantStringType('sv-SE'),
                        new \PHPStan\Type\Constant\ConstantStringType('tr-TR'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-NZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-ZA'),
                        new \PHPStan\Type\Constant\ConstantStringType('ca-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-AT'),
                        new \PHPStan\Type\Constant\ConstantStringType('yue-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ar-AE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fi-FI'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IE'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('cs-CZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-CH'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-SG'),
                    ])),
                    new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('standard'),
                        new \PHPStan\Type\Constant\ConstantStringType('neural'),
                        new \PHPStan\Type\Constant\ConstantStringType('long-form'),
                        new \PHPStan\Type\Constant\ConstantStringType('generative'),
                    ])),
                ])),
                new \PHPStan\Type\StringType(),
            ]),
        ]);
    }
    private function getLexicon(): ?\PHPStan\Type\Type
    {
        return new \PHPStan\Type\Generic\GenericObjectType('Aws\Result', [
            new \PHPStan\Type\Constant\ConstantArrayType([
                new \PHPStan\Type\Constant\ConstantStringType('Lexicon'),
                new \PHPStan\Type\Constant\ConstantStringType('LexiconAttributes'),
            ], [
                new \PHPStan\Type\Constant\ConstantArrayType([
                    new \PHPStan\Type\Constant\ConstantStringType('Content'),
                    new \PHPStan\Type\Constant\ConstantStringType('Name'),
                ], [
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\StringType(),
                ]),
                new \PHPStan\Type\Constant\ConstantArrayType([
                    new \PHPStan\Type\Constant\ConstantStringType('Alphabet'),
                    new \PHPStan\Type\Constant\ConstantStringType('LanguageCode'),
                    new \PHPStan\Type\Constant\ConstantStringType('LastModified'),
                    new \PHPStan\Type\Constant\ConstantStringType('LexiconArn'),
                    new \PHPStan\Type\Constant\ConstantStringType('LexemesCount'),
                    new \PHPStan\Type\Constant\ConstantStringType('Size'),
                ], [
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('arb'),
                        new \PHPStan\Type\Constant\ConstantStringType('cmn-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('cy-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('da-DK'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-DE'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-AU'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB-WLS'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-MX'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-CA'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-FR'),
                        new \PHPStan\Type\Constant\ConstantStringType('is-IS'),
                        new \PHPStan\Type\Constant\ConstantStringType('it-IT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ja-JP'),
                        new \PHPStan\Type\Constant\ConstantStringType('hi-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ko-KR'),
                        new \PHPStan\Type\Constant\ConstantStringType('nb-NO'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-NL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pl-PL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-BR'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-PT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ro-RO'),
                        new \PHPStan\Type\Constant\ConstantStringType('ru-RU'),
                        new \PHPStan\Type\Constant\ConstantStringType('sv-SE'),
                        new \PHPStan\Type\Constant\ConstantStringType('tr-TR'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-NZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-ZA'),
                        new \PHPStan\Type\Constant\ConstantStringType('ca-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-AT'),
                        new \PHPStan\Type\Constant\ConstantStringType('yue-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ar-AE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fi-FI'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IE'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('cs-CZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-CH'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-SG'),
                    ]),
                    new \PHPStan\Type\ObjectType('DateTimeInterface'),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\IntegerType(),
                    new \PHPStan\Type\IntegerType(),
                ]),
            ]),
        ]);
    }
    private function getSpeechSynthesisTask(): ?\PHPStan\Type\Type
    {
        return new \PHPStan\Type\Generic\GenericObjectType('Aws\Result', [
            new \PHPStan\Type\Constant\ConstantArrayType([
                new \PHPStan\Type\Constant\ConstantStringType('SynthesisTask'),
            ], [
                new \PHPStan\Type\Constant\ConstantArrayType([
                    new \PHPStan\Type\Constant\ConstantStringType('Engine'),
                    new \PHPStan\Type\Constant\ConstantStringType('TaskId'),
                    new \PHPStan\Type\Constant\ConstantStringType('TaskStatus'),
                    new \PHPStan\Type\Constant\ConstantStringType('TaskStatusReason'),
                    new \PHPStan\Type\Constant\ConstantStringType('OutputUri'),
                    new \PHPStan\Type\Constant\ConstantStringType('CreationTime'),
                    new \PHPStan\Type\Constant\ConstantStringType('RequestCharacters'),
                    new \PHPStan\Type\Constant\ConstantStringType('SnsTopicArn'),
                    new \PHPStan\Type\Constant\ConstantStringType('LexiconNames'),
                    new \PHPStan\Type\Constant\ConstantStringType('OutputFormat'),
                    new \PHPStan\Type\Constant\ConstantStringType('SampleRate'),
                    new \PHPStan\Type\Constant\ConstantStringType('SpeechMarkTypes'),
                    new \PHPStan\Type\Constant\ConstantStringType('TextType'),
                    new \PHPStan\Type\Constant\ConstantStringType('VoiceId'),
                    new \PHPStan\Type\Constant\ConstantStringType('LanguageCode'),
                ], [
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('standard'),
                        new \PHPStan\Type\Constant\ConstantStringType('neural'),
                        new \PHPStan\Type\Constant\ConstantStringType('long-form'),
                        new \PHPStan\Type\Constant\ConstantStringType('generative'),
                    ]),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('scheduled'),
                        new \PHPStan\Type\Constant\ConstantStringType('inProgress'),
                        new \PHPStan\Type\Constant\ConstantStringType('completed'),
                        new \PHPStan\Type\Constant\ConstantStringType('failed'),
                    ]),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ObjectType('DateTimeInterface'),
                    new \PHPStan\Type\IntegerType(),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\StringType()),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('json'),
                        new \PHPStan\Type\Constant\ConstantStringType('mp3'),
                        new \PHPStan\Type\Constant\ConstantStringType('ogg_vorbis'),
                        new \PHPStan\Type\Constant\ConstantStringType('pcm'),
                    ]),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('sentence'),
                        new \PHPStan\Type\Constant\ConstantStringType('ssml'),
                        new \PHPStan\Type\Constant\ConstantStringType('viseme'),
                        new \PHPStan\Type\Constant\ConstantStringType('word'),
                    ])),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('ssml'),
                        new \PHPStan\Type\Constant\ConstantStringType('text'),
                    ]),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('Aditi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Amy'),
                        new \PHPStan\Type\Constant\ConstantStringType('Astrid'),
                        new \PHPStan\Type\Constant\ConstantStringType('Bianca'),
                        new \PHPStan\Type\Constant\ConstantStringType('Brian'),
                        new \PHPStan\Type\Constant\ConstantStringType('Camila'),
                        new \PHPStan\Type\Constant\ConstantStringType('Carla'),
                        new \PHPStan\Type\Constant\ConstantStringType('Carmen'),
                        new \PHPStan\Type\Constant\ConstantStringType('Celine'),
                        new \PHPStan\Type\Constant\ConstantStringType('Chantal'),
                        new \PHPStan\Type\Constant\ConstantStringType('Conchita'),
                        new \PHPStan\Type\Constant\ConstantStringType('Cristiano'),
                        new \PHPStan\Type\Constant\ConstantStringType('Dora'),
                        new \PHPStan\Type\Constant\ConstantStringType('Emma'),
                        new \PHPStan\Type\Constant\ConstantStringType('Enrique'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ewa'),
                        new \PHPStan\Type\Constant\ConstantStringType('Filiz'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gabrielle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Geraint'),
                        new \PHPStan\Type\Constant\ConstantStringType('Giorgio'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gwyneth'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hans'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ines'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ivy'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jacek'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jan'),
                        new \PHPStan\Type\Constant\ConstantStringType('Joanna'),
                        new \PHPStan\Type\Constant\ConstantStringType('Joey'),
                        new \PHPStan\Type\Constant\ConstantStringType('Justin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Karl'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kendra'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kevin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kimberly'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lea'),
                        new \PHPStan\Type\Constant\ConstantStringType('Liv'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lotte'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lucia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lupe'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mads'),
                        new \PHPStan\Type\Constant\ConstantStringType('Maja'),
                        new \PHPStan\Type\Constant\ConstantStringType('Marlene'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mathieu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Matthew'),
                        new \PHPStan\Type\Constant\ConstantStringType('Maxim'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Miguel'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mizuki'),
                        new \PHPStan\Type\Constant\ConstantStringType('Naja'),
                        new \PHPStan\Type\Constant\ConstantStringType('Nicole'),
                        new \PHPStan\Type\Constant\ConstantStringType('Olivia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Penelope'),
                        new \PHPStan\Type\Constant\ConstantStringType('Raveena'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ricardo'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ruben'),
                        new \PHPStan\Type\Constant\ConstantStringType('Russell'),
                        new \PHPStan\Type\Constant\ConstantStringType('Salli'),
                        new \PHPStan\Type\Constant\ConstantStringType('Seoyeon'),
                        new \PHPStan\Type\Constant\ConstantStringType('Takumi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Tatyana'),
                        new \PHPStan\Type\Constant\ConstantStringType('Vicki'),
                        new \PHPStan\Type\Constant\ConstantStringType('Vitoria'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zeina'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zhiyu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Aria'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ayanda'),
                        new \PHPStan\Type\Constant\ConstantStringType('Arlet'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hannah'),
                        new \PHPStan\Type\Constant\ConstantStringType('Arthur'),
                        new \PHPStan\Type\Constant\ConstantStringType('Daniel'),
                        new \PHPStan\Type\Constant\ConstantStringType('Liam'),
                        new \PHPStan\Type\Constant\ConstantStringType('Pedro'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kajal'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hiujin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Laura'),
                        new \PHPStan\Type\Constant\ConstantStringType('Elin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ida'),
                        new \PHPStan\Type\Constant\ConstantStringType('Suvi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ola'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hala'),
                        new \PHPStan\Type\Constant\ConstantStringType('Andres'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sergio'),
                        new \PHPStan\Type\Constant\ConstantStringType('Remi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Adriano'),
                        new \PHPStan\Type\Constant\ConstantStringType('Thiago'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ruth'),
                        new \PHPStan\Type\Constant\ConstantStringType('Stephen'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kazuha'),
                        new \PHPStan\Type\Constant\ConstantStringType('Tomoko'),
                        new \PHPStan\Type\Constant\ConstantStringType('Niamh'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sofie'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lisa'),
                        new \PHPStan\Type\Constant\ConstantStringType('Isabelle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zayd'),
                        new \PHPStan\Type\Constant\ConstantStringType('Danielle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gregory'),
                        new \PHPStan\Type\Constant\ConstantStringType('Burcu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jitka'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sabrina'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jasmine'),
                    ]),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('arb'),
                        new \PHPStan\Type\Constant\ConstantStringType('cmn-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('cy-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('da-DK'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-DE'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-AU'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB-WLS'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-MX'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-CA'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-FR'),
                        new \PHPStan\Type\Constant\ConstantStringType('is-IS'),
                        new \PHPStan\Type\Constant\ConstantStringType('it-IT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ja-JP'),
                        new \PHPStan\Type\Constant\ConstantStringType('hi-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ko-KR'),
                        new \PHPStan\Type\Constant\ConstantStringType('nb-NO'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-NL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pl-PL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-BR'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-PT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ro-RO'),
                        new \PHPStan\Type\Constant\ConstantStringType('ru-RU'),
                        new \PHPStan\Type\Constant\ConstantStringType('sv-SE'),
                        new \PHPStan\Type\Constant\ConstantStringType('tr-TR'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-NZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-ZA'),
                        new \PHPStan\Type\Constant\ConstantStringType('ca-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-AT'),
                        new \PHPStan\Type\Constant\ConstantStringType('yue-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ar-AE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fi-FI'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IE'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('cs-CZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-CH'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-SG'),
                    ]),
                ]),
            ]),
        ]);
    }
    private function listLexicons(): ?\PHPStan\Type\Type
    {
        return new \PHPStan\Type\Generic\GenericObjectType('Aws\Result', [
            new \PHPStan\Type\Constant\ConstantArrayType([
                new \PHPStan\Type\Constant\ConstantStringType('Lexicons'),
                new \PHPStan\Type\Constant\ConstantStringType('NextToken'),
            ], [
                new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\Constant\ConstantArrayType([
                    new \PHPStan\Type\Constant\ConstantStringType('Name'),
                    new \PHPStan\Type\Constant\ConstantStringType('Attributes'),
                ], [
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\Constant\ConstantArrayType([
                        new \PHPStan\Type\Constant\ConstantStringType('Alphabet'),
                        new \PHPStan\Type\Constant\ConstantStringType('LanguageCode'),
                        new \PHPStan\Type\Constant\ConstantStringType('LastModified'),
                        new \PHPStan\Type\Constant\ConstantStringType('LexiconArn'),
                        new \PHPStan\Type\Constant\ConstantStringType('LexemesCount'),
                        new \PHPStan\Type\Constant\ConstantStringType('Size'),
                    ], [
                        new \PHPStan\Type\StringType(),
                        new \PHPStan\Type\UnionType([
                            new \PHPStan\Type\Constant\ConstantStringType('arb'),
                            new \PHPStan\Type\Constant\ConstantStringType('cmn-CN'),
                            new \PHPStan\Type\Constant\ConstantStringType('cy-GB'),
                            new \PHPStan\Type\Constant\ConstantStringType('da-DK'),
                            new \PHPStan\Type\Constant\ConstantStringType('de-DE'),
                            new \PHPStan\Type\Constant\ConstantStringType('en-AU'),
                            new \PHPStan\Type\Constant\ConstantStringType('en-GB'),
                            new \PHPStan\Type\Constant\ConstantStringType('en-GB-WLS'),
                            new \PHPStan\Type\Constant\ConstantStringType('en-IN'),
                            new \PHPStan\Type\Constant\ConstantStringType('en-US'),
                            new \PHPStan\Type\Constant\ConstantStringType('es-ES'),
                            new \PHPStan\Type\Constant\ConstantStringType('es-MX'),
                            new \PHPStan\Type\Constant\ConstantStringType('es-US'),
                            new \PHPStan\Type\Constant\ConstantStringType('fr-CA'),
                            new \PHPStan\Type\Constant\ConstantStringType('fr-FR'),
                            new \PHPStan\Type\Constant\ConstantStringType('is-IS'),
                            new \PHPStan\Type\Constant\ConstantStringType('it-IT'),
                            new \PHPStan\Type\Constant\ConstantStringType('ja-JP'),
                            new \PHPStan\Type\Constant\ConstantStringType('hi-IN'),
                            new \PHPStan\Type\Constant\ConstantStringType('ko-KR'),
                            new \PHPStan\Type\Constant\ConstantStringType('nb-NO'),
                            new \PHPStan\Type\Constant\ConstantStringType('nl-NL'),
                            new \PHPStan\Type\Constant\ConstantStringType('pl-PL'),
                            new \PHPStan\Type\Constant\ConstantStringType('pt-BR'),
                            new \PHPStan\Type\Constant\ConstantStringType('pt-PT'),
                            new \PHPStan\Type\Constant\ConstantStringType('ro-RO'),
                            new \PHPStan\Type\Constant\ConstantStringType('ru-RU'),
                            new \PHPStan\Type\Constant\ConstantStringType('sv-SE'),
                            new \PHPStan\Type\Constant\ConstantStringType('tr-TR'),
                            new \PHPStan\Type\Constant\ConstantStringType('en-NZ'),
                            new \PHPStan\Type\Constant\ConstantStringType('en-ZA'),
                            new \PHPStan\Type\Constant\ConstantStringType('ca-ES'),
                            new \PHPStan\Type\Constant\ConstantStringType('de-AT'),
                            new \PHPStan\Type\Constant\ConstantStringType('yue-CN'),
                            new \PHPStan\Type\Constant\ConstantStringType('ar-AE'),
                            new \PHPStan\Type\Constant\ConstantStringType('fi-FI'),
                            new \PHPStan\Type\Constant\ConstantStringType('en-IE'),
                            new \PHPStan\Type\Constant\ConstantStringType('nl-BE'),
                            new \PHPStan\Type\Constant\ConstantStringType('fr-BE'),
                            new \PHPStan\Type\Constant\ConstantStringType('cs-CZ'),
                            new \PHPStan\Type\Constant\ConstantStringType('de-CH'),
                            new \PHPStan\Type\Constant\ConstantStringType('en-SG'),
                        ]),
                        new \PHPStan\Type\ObjectType('DateTimeInterface'),
                        new \PHPStan\Type\StringType(),
                        new \PHPStan\Type\IntegerType(),
                        new \PHPStan\Type\IntegerType(),
                    ]),
                ])),
                new \PHPStan\Type\StringType(),
            ]),
        ]);
    }
    private function listSpeechSynthesisTasks(): ?\PHPStan\Type\Type
    {
        return new \PHPStan\Type\Generic\GenericObjectType('Aws\Result', [
            new \PHPStan\Type\Constant\ConstantArrayType([
                new \PHPStan\Type\Constant\ConstantStringType('NextToken'),
                new \PHPStan\Type\Constant\ConstantStringType('SynthesisTasks'),
            ], [
                new \PHPStan\Type\StringType(),
                new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\Constant\ConstantArrayType([
                    new \PHPStan\Type\Constant\ConstantStringType('Engine'),
                    new \PHPStan\Type\Constant\ConstantStringType('TaskId'),
                    new \PHPStan\Type\Constant\ConstantStringType('TaskStatus'),
                    new \PHPStan\Type\Constant\ConstantStringType('TaskStatusReason'),
                    new \PHPStan\Type\Constant\ConstantStringType('OutputUri'),
                    new \PHPStan\Type\Constant\ConstantStringType('CreationTime'),
                    new \PHPStan\Type\Constant\ConstantStringType('RequestCharacters'),
                    new \PHPStan\Type\Constant\ConstantStringType('SnsTopicArn'),
                    new \PHPStan\Type\Constant\ConstantStringType('LexiconNames'),
                    new \PHPStan\Type\Constant\ConstantStringType('OutputFormat'),
                    new \PHPStan\Type\Constant\ConstantStringType('SampleRate'),
                    new \PHPStan\Type\Constant\ConstantStringType('SpeechMarkTypes'),
                    new \PHPStan\Type\Constant\ConstantStringType('TextType'),
                    new \PHPStan\Type\Constant\ConstantStringType('VoiceId'),
                    new \PHPStan\Type\Constant\ConstantStringType('LanguageCode'),
                ], [
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('standard'),
                        new \PHPStan\Type\Constant\ConstantStringType('neural'),
                        new \PHPStan\Type\Constant\ConstantStringType('long-form'),
                        new \PHPStan\Type\Constant\ConstantStringType('generative'),
                    ]),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('scheduled'),
                        new \PHPStan\Type\Constant\ConstantStringType('inProgress'),
                        new \PHPStan\Type\Constant\ConstantStringType('completed'),
                        new \PHPStan\Type\Constant\ConstantStringType('failed'),
                    ]),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ObjectType('DateTimeInterface'),
                    new \PHPStan\Type\IntegerType(),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\StringType()),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('json'),
                        new \PHPStan\Type\Constant\ConstantStringType('mp3'),
                        new \PHPStan\Type\Constant\ConstantStringType('ogg_vorbis'),
                        new \PHPStan\Type\Constant\ConstantStringType('pcm'),
                    ]),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('sentence'),
                        new \PHPStan\Type\Constant\ConstantStringType('ssml'),
                        new \PHPStan\Type\Constant\ConstantStringType('viseme'),
                        new \PHPStan\Type\Constant\ConstantStringType('word'),
                    ])),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('ssml'),
                        new \PHPStan\Type\Constant\ConstantStringType('text'),
                    ]),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('Aditi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Amy'),
                        new \PHPStan\Type\Constant\ConstantStringType('Astrid'),
                        new \PHPStan\Type\Constant\ConstantStringType('Bianca'),
                        new \PHPStan\Type\Constant\ConstantStringType('Brian'),
                        new \PHPStan\Type\Constant\ConstantStringType('Camila'),
                        new \PHPStan\Type\Constant\ConstantStringType('Carla'),
                        new \PHPStan\Type\Constant\ConstantStringType('Carmen'),
                        new \PHPStan\Type\Constant\ConstantStringType('Celine'),
                        new \PHPStan\Type\Constant\ConstantStringType('Chantal'),
                        new \PHPStan\Type\Constant\ConstantStringType('Conchita'),
                        new \PHPStan\Type\Constant\ConstantStringType('Cristiano'),
                        new \PHPStan\Type\Constant\ConstantStringType('Dora'),
                        new \PHPStan\Type\Constant\ConstantStringType('Emma'),
                        new \PHPStan\Type\Constant\ConstantStringType('Enrique'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ewa'),
                        new \PHPStan\Type\Constant\ConstantStringType('Filiz'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gabrielle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Geraint'),
                        new \PHPStan\Type\Constant\ConstantStringType('Giorgio'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gwyneth'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hans'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ines'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ivy'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jacek'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jan'),
                        new \PHPStan\Type\Constant\ConstantStringType('Joanna'),
                        new \PHPStan\Type\Constant\ConstantStringType('Joey'),
                        new \PHPStan\Type\Constant\ConstantStringType('Justin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Karl'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kendra'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kevin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kimberly'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lea'),
                        new \PHPStan\Type\Constant\ConstantStringType('Liv'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lotte'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lucia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lupe'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mads'),
                        new \PHPStan\Type\Constant\ConstantStringType('Maja'),
                        new \PHPStan\Type\Constant\ConstantStringType('Marlene'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mathieu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Matthew'),
                        new \PHPStan\Type\Constant\ConstantStringType('Maxim'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Miguel'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mizuki'),
                        new \PHPStan\Type\Constant\ConstantStringType('Naja'),
                        new \PHPStan\Type\Constant\ConstantStringType('Nicole'),
                        new \PHPStan\Type\Constant\ConstantStringType('Olivia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Penelope'),
                        new \PHPStan\Type\Constant\ConstantStringType('Raveena'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ricardo'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ruben'),
                        new \PHPStan\Type\Constant\ConstantStringType('Russell'),
                        new \PHPStan\Type\Constant\ConstantStringType('Salli'),
                        new \PHPStan\Type\Constant\ConstantStringType('Seoyeon'),
                        new \PHPStan\Type\Constant\ConstantStringType('Takumi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Tatyana'),
                        new \PHPStan\Type\Constant\ConstantStringType('Vicki'),
                        new \PHPStan\Type\Constant\ConstantStringType('Vitoria'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zeina'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zhiyu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Aria'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ayanda'),
                        new \PHPStan\Type\Constant\ConstantStringType('Arlet'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hannah'),
                        new \PHPStan\Type\Constant\ConstantStringType('Arthur'),
                        new \PHPStan\Type\Constant\ConstantStringType('Daniel'),
                        new \PHPStan\Type\Constant\ConstantStringType('Liam'),
                        new \PHPStan\Type\Constant\ConstantStringType('Pedro'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kajal'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hiujin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Laura'),
                        new \PHPStan\Type\Constant\ConstantStringType('Elin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ida'),
                        new \PHPStan\Type\Constant\ConstantStringType('Suvi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ola'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hala'),
                        new \PHPStan\Type\Constant\ConstantStringType('Andres'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sergio'),
                        new \PHPStan\Type\Constant\ConstantStringType('Remi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Adriano'),
                        new \PHPStan\Type\Constant\ConstantStringType('Thiago'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ruth'),
                        new \PHPStan\Type\Constant\ConstantStringType('Stephen'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kazuha'),
                        new \PHPStan\Type\Constant\ConstantStringType('Tomoko'),
                        new \PHPStan\Type\Constant\ConstantStringType('Niamh'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sofie'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lisa'),
                        new \PHPStan\Type\Constant\ConstantStringType('Isabelle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zayd'),
                        new \PHPStan\Type\Constant\ConstantStringType('Danielle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gregory'),
                        new \PHPStan\Type\Constant\ConstantStringType('Burcu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jitka'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sabrina'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jasmine'),
                    ]),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('arb'),
                        new \PHPStan\Type\Constant\ConstantStringType('cmn-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('cy-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('da-DK'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-DE'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-AU'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB-WLS'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-MX'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-CA'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-FR'),
                        new \PHPStan\Type\Constant\ConstantStringType('is-IS'),
                        new \PHPStan\Type\Constant\ConstantStringType('it-IT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ja-JP'),
                        new \PHPStan\Type\Constant\ConstantStringType('hi-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ko-KR'),
                        new \PHPStan\Type\Constant\ConstantStringType('nb-NO'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-NL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pl-PL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-BR'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-PT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ro-RO'),
                        new \PHPStan\Type\Constant\ConstantStringType('ru-RU'),
                        new \PHPStan\Type\Constant\ConstantStringType('sv-SE'),
                        new \PHPStan\Type\Constant\ConstantStringType('tr-TR'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-NZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-ZA'),
                        new \PHPStan\Type\Constant\ConstantStringType('ca-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-AT'),
                        new \PHPStan\Type\Constant\ConstantStringType('yue-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ar-AE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fi-FI'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IE'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('cs-CZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-CH'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-SG'),
                    ]),
                ])),
            ]),
        ]);
    }
    private function putLexicon(): ?\PHPStan\Type\Type
    {
        return new \PHPStan\Type\Generic\GenericObjectType('Aws\Result', [
            new \PHPStan\Type\Constant\ConstantArrayType([], []),
        ]);
    }
    private function startSpeechSynthesisTask(): ?\PHPStan\Type\Type
    {
        return new \PHPStan\Type\Generic\GenericObjectType('Aws\Result', [
            new \PHPStan\Type\Constant\ConstantArrayType([
                new \PHPStan\Type\Constant\ConstantStringType('SynthesisTask'),
            ], [
                new \PHPStan\Type\Constant\ConstantArrayType([
                    new \PHPStan\Type\Constant\ConstantStringType('Engine'),
                    new \PHPStan\Type\Constant\ConstantStringType('TaskId'),
                    new \PHPStan\Type\Constant\ConstantStringType('TaskStatus'),
                    new \PHPStan\Type\Constant\ConstantStringType('TaskStatusReason'),
                    new \PHPStan\Type\Constant\ConstantStringType('OutputUri'),
                    new \PHPStan\Type\Constant\ConstantStringType('CreationTime'),
                    new \PHPStan\Type\Constant\ConstantStringType('RequestCharacters'),
                    new \PHPStan\Type\Constant\ConstantStringType('SnsTopicArn'),
                    new \PHPStan\Type\Constant\ConstantStringType('LexiconNames'),
                    new \PHPStan\Type\Constant\ConstantStringType('OutputFormat'),
                    new \PHPStan\Type\Constant\ConstantStringType('SampleRate'),
                    new \PHPStan\Type\Constant\ConstantStringType('SpeechMarkTypes'),
                    new \PHPStan\Type\Constant\ConstantStringType('TextType'),
                    new \PHPStan\Type\Constant\ConstantStringType('VoiceId'),
                    new \PHPStan\Type\Constant\ConstantStringType('LanguageCode'),
                ], [
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('standard'),
                        new \PHPStan\Type\Constant\ConstantStringType('neural'),
                        new \PHPStan\Type\Constant\ConstantStringType('long-form'),
                        new \PHPStan\Type\Constant\ConstantStringType('generative'),
                    ]),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('scheduled'),
                        new \PHPStan\Type\Constant\ConstantStringType('inProgress'),
                        new \PHPStan\Type\Constant\ConstantStringType('completed'),
                        new \PHPStan\Type\Constant\ConstantStringType('failed'),
                    ]),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ObjectType('DateTimeInterface'),
                    new \PHPStan\Type\IntegerType(),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\StringType()),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('json'),
                        new \PHPStan\Type\Constant\ConstantStringType('mp3'),
                        new \PHPStan\Type\Constant\ConstantStringType('ogg_vorbis'),
                        new \PHPStan\Type\Constant\ConstantStringType('pcm'),
                    ]),
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ArrayType(new \PHPStan\Type\IntegerType(), new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('sentence'),
                        new \PHPStan\Type\Constant\ConstantStringType('ssml'),
                        new \PHPStan\Type\Constant\ConstantStringType('viseme'),
                        new \PHPStan\Type\Constant\ConstantStringType('word'),
                    ])),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('ssml'),
                        new \PHPStan\Type\Constant\ConstantStringType('text'),
                    ]),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('Aditi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Amy'),
                        new \PHPStan\Type\Constant\ConstantStringType('Astrid'),
                        new \PHPStan\Type\Constant\ConstantStringType('Bianca'),
                        new \PHPStan\Type\Constant\ConstantStringType('Brian'),
                        new \PHPStan\Type\Constant\ConstantStringType('Camila'),
                        new \PHPStan\Type\Constant\ConstantStringType('Carla'),
                        new \PHPStan\Type\Constant\ConstantStringType('Carmen'),
                        new \PHPStan\Type\Constant\ConstantStringType('Celine'),
                        new \PHPStan\Type\Constant\ConstantStringType('Chantal'),
                        new \PHPStan\Type\Constant\ConstantStringType('Conchita'),
                        new \PHPStan\Type\Constant\ConstantStringType('Cristiano'),
                        new \PHPStan\Type\Constant\ConstantStringType('Dora'),
                        new \PHPStan\Type\Constant\ConstantStringType('Emma'),
                        new \PHPStan\Type\Constant\ConstantStringType('Enrique'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ewa'),
                        new \PHPStan\Type\Constant\ConstantStringType('Filiz'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gabrielle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Geraint'),
                        new \PHPStan\Type\Constant\ConstantStringType('Giorgio'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gwyneth'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hans'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ines'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ivy'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jacek'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jan'),
                        new \PHPStan\Type\Constant\ConstantStringType('Joanna'),
                        new \PHPStan\Type\Constant\ConstantStringType('Joey'),
                        new \PHPStan\Type\Constant\ConstantStringType('Justin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Karl'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kendra'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kevin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kimberly'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lea'),
                        new \PHPStan\Type\Constant\ConstantStringType('Liv'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lotte'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lucia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lupe'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mads'),
                        new \PHPStan\Type\Constant\ConstantStringType('Maja'),
                        new \PHPStan\Type\Constant\ConstantStringType('Marlene'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mathieu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Matthew'),
                        new \PHPStan\Type\Constant\ConstantStringType('Maxim'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Miguel'),
                        new \PHPStan\Type\Constant\ConstantStringType('Mizuki'),
                        new \PHPStan\Type\Constant\ConstantStringType('Naja'),
                        new \PHPStan\Type\Constant\ConstantStringType('Nicole'),
                        new \PHPStan\Type\Constant\ConstantStringType('Olivia'),
                        new \PHPStan\Type\Constant\ConstantStringType('Penelope'),
                        new \PHPStan\Type\Constant\ConstantStringType('Raveena'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ricardo'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ruben'),
                        new \PHPStan\Type\Constant\ConstantStringType('Russell'),
                        new \PHPStan\Type\Constant\ConstantStringType('Salli'),
                        new \PHPStan\Type\Constant\ConstantStringType('Seoyeon'),
                        new \PHPStan\Type\Constant\ConstantStringType('Takumi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Tatyana'),
                        new \PHPStan\Type\Constant\ConstantStringType('Vicki'),
                        new \PHPStan\Type\Constant\ConstantStringType('Vitoria'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zeina'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zhiyu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Aria'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ayanda'),
                        new \PHPStan\Type\Constant\ConstantStringType('Arlet'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hannah'),
                        new \PHPStan\Type\Constant\ConstantStringType('Arthur'),
                        new \PHPStan\Type\Constant\ConstantStringType('Daniel'),
                        new \PHPStan\Type\Constant\ConstantStringType('Liam'),
                        new \PHPStan\Type\Constant\ConstantStringType('Pedro'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kajal'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hiujin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Laura'),
                        new \PHPStan\Type\Constant\ConstantStringType('Elin'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ida'),
                        new \PHPStan\Type\Constant\ConstantStringType('Suvi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ola'),
                        new \PHPStan\Type\Constant\ConstantStringType('Hala'),
                        new \PHPStan\Type\Constant\ConstantStringType('Andres'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sergio'),
                        new \PHPStan\Type\Constant\ConstantStringType('Remi'),
                        new \PHPStan\Type\Constant\ConstantStringType('Adriano'),
                        new \PHPStan\Type\Constant\ConstantStringType('Thiago'),
                        new \PHPStan\Type\Constant\ConstantStringType('Ruth'),
                        new \PHPStan\Type\Constant\ConstantStringType('Stephen'),
                        new \PHPStan\Type\Constant\ConstantStringType('Kazuha'),
                        new \PHPStan\Type\Constant\ConstantStringType('Tomoko'),
                        new \PHPStan\Type\Constant\ConstantStringType('Niamh'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sofie'),
                        new \PHPStan\Type\Constant\ConstantStringType('Lisa'),
                        new \PHPStan\Type\Constant\ConstantStringType('Isabelle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Zayd'),
                        new \PHPStan\Type\Constant\ConstantStringType('Danielle'),
                        new \PHPStan\Type\Constant\ConstantStringType('Gregory'),
                        new \PHPStan\Type\Constant\ConstantStringType('Burcu'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jitka'),
                        new \PHPStan\Type\Constant\ConstantStringType('Sabrina'),
                        new \PHPStan\Type\Constant\ConstantStringType('Jasmine'),
                    ]),
                    new \PHPStan\Type\UnionType([
                        new \PHPStan\Type\Constant\ConstantStringType('arb'),
                        new \PHPStan\Type\Constant\ConstantStringType('cmn-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('cy-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('da-DK'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-DE'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-AU'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-GB-WLS'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-MX'),
                        new \PHPStan\Type\Constant\ConstantStringType('es-US'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-CA'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-FR'),
                        new \PHPStan\Type\Constant\ConstantStringType('is-IS'),
                        new \PHPStan\Type\Constant\ConstantStringType('it-IT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ja-JP'),
                        new \PHPStan\Type\Constant\ConstantStringType('hi-IN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ko-KR'),
                        new \PHPStan\Type\Constant\ConstantStringType('nb-NO'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-NL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pl-PL'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-BR'),
                        new \PHPStan\Type\Constant\ConstantStringType('pt-PT'),
                        new \PHPStan\Type\Constant\ConstantStringType('ro-RO'),
                        new \PHPStan\Type\Constant\ConstantStringType('ru-RU'),
                        new \PHPStan\Type\Constant\ConstantStringType('sv-SE'),
                        new \PHPStan\Type\Constant\ConstantStringType('tr-TR'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-NZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-ZA'),
                        new \PHPStan\Type\Constant\ConstantStringType('ca-ES'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-AT'),
                        new \PHPStan\Type\Constant\ConstantStringType('yue-CN'),
                        new \PHPStan\Type\Constant\ConstantStringType('ar-AE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fi-FI'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-IE'),
                        new \PHPStan\Type\Constant\ConstantStringType('nl-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('fr-BE'),
                        new \PHPStan\Type\Constant\ConstantStringType('cs-CZ'),
                        new \PHPStan\Type\Constant\ConstantStringType('de-CH'),
                        new \PHPStan\Type\Constant\ConstantStringType('en-SG'),
                    ]),
                ]),
            ]),
        ]);
    }
    private function synthesizeSpeech(): ?\PHPStan\Type\Type
    {
        return new \PHPStan\Type\Generic\GenericObjectType('Aws\Result', [
            new \PHPStan\Type\Constant\ConstantArrayType([
                new \PHPStan\Type\Constant\ConstantStringType('AudioStream'),
                new \PHPStan\Type\Constant\ConstantStringType('ContentType'),
                new \PHPStan\Type\Constant\ConstantStringType('RequestCharacters'),
            ], [
                new \PHPStan\Type\UnionType([
                    new \PHPStan\Type\StringType(),
                    new \PHPStan\Type\ResourceType(),
                    new \PHPStan\Type\ObjectType('Psr\Http\Message\StreamInterface'),
                ]),
                new \PHPStan\Type\StringType(),
                new \PHPStan\Type\IntegerType(),
            ]),
        ]);
    }
}